config/routes.rb
Rails.application.routes.draw do
  get 'receipts/index'

  get 'receipts/create'

  root to: 'welcome#index'

  resources :stores

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  post '/stores/:id/update_token', to: 'stores#update_token', as: 'update_token'

  get '/receipts', to: 'receipts#index', as: 'all_receipts'
  post '/receipts', to: 'receipts#create', as: 'create_receipt' 

  get '/account', to: 'stores#show', as: 'account'
end

app/models/api_token.rb
class ApiToken < ActiveRecord::Base
	belongs_to :store

	validates :hex_value, uniqueness: true, presence: true
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
	belongs_to :store
end

app/models/store.rb
class Store < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true

	has_secure_password
	has_one :api_token
	has_many :receipts
	
	def self.confirm(params)
    @store = Store.find_by({email: params[:email]})
    @store.try(:authenticate, params[:password])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include StoresHelper
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
	include ReceiptsHelper
	skip_before_filter :verify_authenticity_token
	before_filter :restrict_access
  
  def index
  	store = get_store(params[:api_token])
		@receipts = store.receipts
		respond_to do |format|
			format.json { render json: @receipts }
		end
  end

  def create
		@store = get_store(params[:api_token])
		@params = receipt_params
		@receipt = @store.receipts.create(@params)
	end

  private
    def restrict_access
      api_key = ApiToken.find_by_hex_value(params[:api_token])
      head :unauthorized unless api_key
    end

    def receipt_params
      params.require(:receipt).permit(:transaction_number, :payment_method, :subtotal, :tip, :total, :customer_info, :items, :item_count, :taxes, :tender_amount, :change_due)
    end
end

{"transaction_number":"12345677899","payment_method":"amex 1234","subtotal":10,"tip":2,"taxes":1,"total":13,"customer_info":{"first_name":"Andreas","last_name":"Bloomquist","member_id":1},"items":[{"sku":"ABC123","description":"Super Computer","upc":"012345678901","serial_number":"123ABC123","price":"1000.00","taxcode":"A"},{"sku":"CDE456","description":"t-shirt","upc":"222333222333","price":"12.00","qty":"4","taxcode":"A"}],"item_count":2,"tender_amount":20,"change_due":7}

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def index
	end

	def new
		@store = Store.new
	end

	def create
		@store = Store.confirm(params.require(:store).permit(:email, :name, :password, :password_confirmation))
		if @store 
			login(@store)
			flash[:success] = "Successfully logged in"
			redirect_to account_path
		else
			flash[:error] = "Invalid email or password"
			redirect_to login_path
		end
	end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_filter :redirect_unauthenticated, except: [:new, :create]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = current_store
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        login(@store)
        generate_api_key
        format.html { redirect_to account_path, success: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to account_path, success: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_token
    reset_api_token
    redirect_to account_path
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(session[:store_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper

	def get_store(api_key)
		api_record = ApiToken.find_by(hex_value: api_key)
		store = Store.find(api_record.store_id)
		return store
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def login(store)
    session[:store_id] = store.id
    @current_store = store
  end

  def current_store
    return false if session[:store_id] == nil
    @current_store ||= Store.find(session[:store_id])
  end

  def logged_in?
    if current_store == false
      return false
    else
      return true
    end
  end

  def logout
    @current_store = session[:store_id] = nil
    redirect_to root_path
  end

  def redirect_unauthenticated
    unless logged_in?
      flash[:alert] = "Sorry, you must be logged in to see this content"
      return redirect_to login_path
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
	require 'securerandom'

	def generate_api_key
		api_key = SecureRandom.uuid
		store = current_store.id
		token = ApiToken.create(store_id: store, hex_value: api_key)
	end

	def reset_api_token
		@store = Store.find(params[:id])
		new_key = SecureRandom.uuid
		@store.api_token.update_attribute(:hex_value, new_key)
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav>
	<% if logged_in? %>
		<%= link_to "Account", current_store %>
		<%= link_to "Logout", logout_path %>
	<% else %>
		<%= link_to "Login", login_path %> |
		<%= link_to "Sign up", new_store_path %>
	<% end %>
	
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="row">
      <div class="small-12 large-12 columns">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/receipts/create.html.erb
<h1>Receipts#create</h1>
<p>Find me in app/views/receipts/create.html.erb</p>

app/views/receipts/index.html.erb
<h1>Receipts#index</h1>
<p>Find me in app/views/receipts/index.html.erb</p>

app/views/stores/_form.html.erb
<%= form_for(@store, remote: true) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<div ng-app="AccountApp">
	<div ng-controller="MainCtrl">
		{{greeting}}
		{{current_user.name}}

		<p id="notice"><%= notice %></p>

		<h1><%= @store.name %></h1>

		<p>
			<strong>Email:</strong>
			<%= @store.email %>
		</p>

		<p>
			<strong>API Key:</strong>
			<%= @store.api_token.hex_value %>
			<%= button_to "Update key", update_token_path(@store.id), class: "button" %>


		<!-- Edit Store Info Modal -->
		<a href="#" data-reveal-id="myModal">Edit</a>

		<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  		<h2 id="modalTitle">Edit your store</h2>
  		<%= render 'form' %>
  		<a class="close-reveal-modal" aria-label="Close">&#215;</a>
		</div>
		
		<div>
			<button ng-hide="receipts" ng-click="getReceipts()">  Show Receipts </button>
		</div>
		<div>
			<button ng-show="receipts" ng-click="hideReceipts()"> Hide Receipts</button>
		</div>
		<div>
			<button> Add Receipt
			</button>
		</div>
		<div ng-show="receipts">
			Total Number of Receipts: {{receipts.length}}
		</div>
		<div ng-repeat="r in receipts" class="receipt">
			<strong>Date of service:</strong> {{r.created_at | date}}
			<br>
			<strong>Transaction #:</strong> {{r.transaction_number}}
			<br>
			<strong>Payment Method:</strong> {{r.payment_method}}
			<br>
			<strong>Subtotal:</strong> {{r.subtotal | currency}}
			<br>
			<strong>Tip:</strong> {{r.tip | currency}}
			<br>
			<strong>Total:</strong> {{r.total | currency}}

		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>